---
- name: Install grafana
  apt:
    name: "grafana={{ hs_grafana_version }}"
    state: present

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: true
    state: started

